# Generated by Django 4.2.3 on 2024-01-31 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washiriki',
            name='Aina',
            field=models.CharField(choices=[('Mshiriki', 'Mshiriki'), ('mzee wa kanisa', 'mzee wa kanisa'), ('karani', 'karani'), ('shemasi mkuu wa kiume', 'shemasi mkuu wa kiume'), ('shemasi mkuu wa kike', 'shemasi mkuu wa kike')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
