# Generated by Django 4.2.3 on 2024-01-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_washiriki_aina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washiriki',
            old_name='user',
            new_name='Namba_ya_Ushirika',
        ),
    ]
